### ISSUE TITLE
Public Key Not received Properly

### ISSUE THREAD

**Issue by imkumarsaurabh** [Sitecore/sitecore-xamarin-pcl-sdk#6]
Hi I have downloaded the Sitecore mobile SDK and trying to test, but I am getting "[Sitecore Mobile SDK] Public key not received properly" Error in this line "var response = await session.AuthenticateAsync();"
 below is code I am using:
`var instanceUrl = "MyURL;

				using (var credentials = new SecureStringPasswordProvider("username","password"))
			using (
				var session = SitecoreWebApiSessionBuilder.AuthenticatedSessionWithHost(instanceUrl)
				.Credentials(credentials)
				.DefaultLanguage("en-US")
				.Site("/sitecore/shell")
				.BuildSession());`

I checked previous issue and found that instanceUrl\Website\App_Config\Include\Sitecore.ItemWebApi.config was not there, so i downloaded from git and placed on that location. with below setting:
`<site name="website">
        <patch:attribute name="itemwebapi.mode">StandardSecurity</patch:attribute>
        <patch:attribute name="itemwebapi.access">ReadOnly</patch:attribute>
        <patch:attribute name="itemwebapi.allowanonymousaccess">true</patch:attribute>
</site>`

Still issue is same.I am using Xamarin.iOS and have done host entry on mac to map the sticker instance Url.

Please help.

**Comment by Igor-Khomich** [comment]
Hi,

Looks like you have no WebApi module installed on your instance. You can find installation package and instructions by this link.
https://sdn.sitecore.net/Products/Sitecore%20Item%20Web%20API/SitecoreItemWebApi12.aspx
Thanks.

**Comment by imkumarsaurabh** [comment]
Hi Igor,

Thanks for your reply. I logged in inside sdn and tried downloading the module but it gave me following error
"Permission to the Requested document was denied".

FYI: we are using Sitecore 7.2
Please guide.

Thanks,
Saurabh

**Comment by Igor-Khomich** [comment]
Please contact with the Sitecore Support
https://kb.sitecore.net/articles/654910

I have no access to the clients info so I can't help you in this question.
Thanks.
