### ISSUE TITLE
Could not add Sitecore Xamarin NuGet packages into Xamarin Forms Portable Project in Visual Studio 2015

### ISSUE THREAD

**Issue by chaturangar** [Sitecore/sitecore-xamarin-pcl-sdk#7]
When try to add Sitecore.MobileSDK.Xamarin NuGet packge into Xamarin Forms Portable project, it failes with following error

Severity	Code	Description	Project	File	Line	Suppression State
Error		
Could not install package 'Sitecore.MobileSDK.Xamarin 1.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by kzotin** [comment]
Hi,
Could you please send us archived solution?

Thanks.

**Comment by chaturangar** [comment]
I have uploaded the archived solution to dropbox. it is quite big though since i compress full solution folder.
https://www.dropbox.com/s/t71d4yexjnpzn5o/TestApp.zip?dl=0

**Comment by chaturangar** [comment]
Hi,
Do you have any idea on why this is happening ?
Following is the message i'm getting on nuget package installation failed.

Error : Could not install package 'Sitecore.MobileSDK.Xamarin 1.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

Your help would be highly appreciate..
Thank you.

**Comment by Igor-Khomich** [comment]
Hi Chaturangar,

Sorry for the late answer.
I've checked you project and figured out that we have no assembly to support the latest Microsoft "ASP.Net Core 1.0" platform.
We will release the new nuget package with updated assemblies in a few days.
And, as temporary decision, you can use source codes of the Sitecore MobileSDK in your project.

Thanks.

**Comment by Igor-Khomich** [comment]
Hi Chaturangar,

Please try the following updates:
Sitecore.MobileSDK.Xamarin 1.0.2-beta1
Sitecore.MobileSDK.PasswordProvider 1.0.3-beta1

Thanks.

**Comment by chaturangar** [comment]
Hi,
Thank you for the update. 
I tried it and it successfully installed into VS2015 project.

(Earlier, as a workaround, I was able to get the nuget packages installed into solution by using Xamarin Studio and then moved to VS)

Thanks again for the update and help.
/Chaturanga

**Comment by Igor-Khomich** [comment]
Hi,

You are welcome.

>Earlier, as a workaround, I was able to get the nuget packages installed into solution by using Xamarin Studio and then moved to VS

It's because of different project types created by default.
